spring:
  application:
    name: scott
  config:
    #.env file outside of the project directory
    # contains ENVIRONMENT=local

    import: optional:file:../local-config/.env[.properties]

    #sets the Spring profile from the value in the .env file, which only exists on local machine.
    #when in docker there's an env variable with SPRING_PROFILES_ACTIVE=docker, see grafana/docker-compose.yaml

  profiles:
    active: "${ENVIRONMENT:default}"

  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: ALWAYS


logged:
  icons: true
  use-utf8: false

  mdc:
    enabled: true
    args-template: "({c}){k}:{v}"
  slf4j:
    args-template: "({c}){k}:{v}"
    depth-icon-color: YELLOW

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,configprops,beans,mappings,prometheus
      base-path: /actuator
  endpoint:
    prometheus:
      access: unrestricted
    health:
      show-details: always
      show-components: always
    info:
      access: unrestricted
    metrics:
      access: unrestricted
    env:
      access: unrestricted
    configprops:
      access: unrestricted
    beans:
      access: unrestricted
    mappings:
      access: unrestricted