spring:
  application:
    name: scott
  main:
    allow-bean-definition-overriding: true

logged:
  icons: true
  color: true
  use-utf8: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5level : %msg%n"
